spring:
  profiles:
    include:
      - mail
      - datasource
      - secret
      - s3
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: UTC
    open-in-view: false