spring:
  config:
    import:
      - classpath:config/application-mail.properties
s3:
  credentials:
    access-key: ${s3.credentials.access-key}
    secret-key: ${s3.credentials.secret-key}
    region: ${s3.credentials.region}
    bucket: ${s3.credentials.bucket}