spring:
  config:
    import:
      - classpath:config/application-secret.properties

secret:
  discord:
    web-hook: ${secret.discord.web-hook}

jwt:
  access:
    secret: ${jwt.access.secret}
    expiration: ${jwt.access.expiration}
  refresh:
    secret: ${jwt.refresh.secret}
    expiration: ${jwt.refresh.expiration}

api:
  server: ${api.server}